spring:

  application:
    name: forex-service

  datasource:
    username: dew
    password: pass
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:forex-service

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    root: WARN
  file:
    name: forex-service.log

import-service:
  apilayer:
    name: "APILayer"
    key: "nWaLfRnRmN2khGoXLro71fBMQ7WhPEiq"
    url: "https://api.apilayer.com/exchangerates_data/"
  currency:
    name: "Currencyapi"
    key: "ogDB3HvDmNZC08JI7xn6XlTLn5DDbRSnD12VYaKu"
    url: "https://api.currencyapi.com/v3/"
  import-crone: "0 5 0 * * ?"